name: GlobalAuth
version: 0.0.1
author: samrg472 <samrg472@gmail.com>
homepage: https://github.com/DirectMyFile/GlobalAuth
description: An LDAP replacement for authentication systems.
environment:
  sdk: ">=1.8.0"
dependencies:
  args: ">=0.12.2+1 <0.13.0"
